spring:
  profiles:
    active: db
  application:
    name: cloud-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true