mybatis-plus:
  mapper-locations: classpath*:mappers/*.xml
  global-config:
    db-config:
      update-strategy: not_empty
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_project?serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    org.myproject.boot.application.admin.db.mapper: debug