mybatis:
  mapper-locations: classpath*:mappers/*.xml
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_project_goods?serverTimezone=Asia/Shanghai
    type: cn.beecp.BeeDataSource