mybatis:
  type-handlers-package: org.myproject.application.admin.db.typehander
  type-aliases-package: org.myproject.boot.application.admin.db.base.pagehelper.pojo
  type-aliases-super-type: org.myproject.mybatis.pagehelper.pojo.BaseEntity
  mapper-locations: classpath*:mappers/*.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_project?serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver