spring:
  application:
    name: my-cloud-application-admin-01-mybatis-base-pagehelper-01
  profiles:
    active: db,mvc
server:
  port: 8081
eureka:
  client:
    service-url: http://localhost:8080/eureka
