mybatis:
  mapper-locations: classpath*:mappers/*.xml
  type-aliases-super-type: org.myproject.boot.application.admin.db.pojo.TbBaseEntity
  type-aliases-package: org.myproject.boot.application.admin.db.pojo
  executor-type: reuse
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_project_admin?serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource